#!/bin/bash

PWD=`pwd`
OUT=""
while [ ! "${OUT}" ]
do
    OUT=$(ls -l "${PWD}"/setup.py 2> /dev/null)
    if [[ ${#OUT} -gt 0 ]]
        then 
        echo "${PWD}"

        cd ${PWD}
        sudo python setup.py clean
        sudo python setup.py install
        wait ${!}
        cd "${PWD}/tests"
        `nosetests`
        wait ${!}

        cd ..
        find . -name '*.pyc' -delete
        break
    fi
    PWD=$(dirname "${PWD}")
    if [[ "${PWD}" == '/' ]]
        then
        break
    fi
done

